version: 2
sources:
- name: staging_patient
  schema: staging_patient
  tables:
  - name: Form_Responses_1
    identifier: Form_Responses_1
    description: ''
- name: staging_medicines
  schema: staging_medicines
  tables:
  - name: April
    identifier: April
  - name: August
    identifier: August
  - name: December
    identifier: December
  - name: January
    identifier: January
  - name: July
    identifier: July
  - name: June
    identifier: June
  - name: May
    identifier: May
  - name: November
    identifier: November
  - name: October
    identifier: October
  - name: September
    identifier: September
- name: staging_health_camp
  schema: staging_health_camp
  tables:
  - name: Form_Responses_1
    identifier: Form_Responses_1
- name: staging_college
  schema: staging_college
  tables:
  - name: Form_Responses_1
    identifier: Form_Responses_1
  - name: Data
    identifier: Data

- name: test
  schema: staging_mock2
  tables:
  - name: mock_data_csv
    identifier: MOCK_DATA_csv

- name: staging_mock1
  schema: staging_mock1
  tables:
  - name: Mock_sheet
    identifier: MOCK_DATA_csv


    
    

