{{ config(
    materialized='table',
    tags=["patient_data", "2025-2026"]
  ) }}
  
with source as (
    select * from {{ source('staging_patient', 'Form_Responses_1') }}
),

renamed as (
    select
        "Age",
        "ORS",
        "Area",
        "Month",
        "Nipple",
        "Hyponid",
        "Oral__L",
        "Azito_FS",
        "Diclogem",
        "Meftadol",
        "Age_Group",
        "Diagnosis",
        "Timestamp",
        case 
            when lower(trim("Month")) = 'aug' then '05 - august'
            when lower(trim("Month")) = 'sep' then '06 - september'
            when lower(trim("Month")) = 'may' then '02 - may'
            when lower(trim("Month")) = 'nov' then '08 - november'
            when lower(trim("Month")) = 'jul' then '04 - july'
            when lower(trim("Month")) = 'jun' then '03 - june'
            when lower(trim("Month")) = 'oct' then '07 - october'
            else "Month"
        end as month_formatted,
        "Any_remark",
        "Clobego_GM",
        "Flucon_150",
        "Ironfast_Z",
        "Myna_UID_",
        "Azinetra_Kit",
        "Calcipic_500",
        "Case_History",
        "Cazole_Forte",
        "Nor_TZ_200mg",
        "Patient_type",
        "Phone_number",
        "Date_of_visit",
        "Follow_up_date",
        "Investigations",
        "Changes_in_skin",
        "Family_planning",
        "Doxy__Doxylac_B_",
        "Follow_up_needed",
        "M2__Tone_Tablets",
        "Data_entry_Person",
        "Omee_20__Omak_20_",
        "Diagnosis_Cleaning",
        "Name_of_the_Doctor",
        "Symptomatic_Relief",
        "Name_of_the_Patient",
        "Chief_Complaint_type",
        "Case_History_Cleaning",
        "Family_planning__Both_",
        "Follow_up_Patient_type",
        "UID_for_cross_checking",
        "Itra_100__Itrajohn_100_",
        "Itra_200__Itrajohn_200_",
        "Transemic_acid__TRN_500_",
        "Letsi_2_5__Letroquin_2_5_",
        "Levocet__AZINE_L__Levophine_",
        "3_Kit__Azinetra_Kit__Azito_FS_",
        "Progestrone_200__Legestro_200_",
        "Rs__20_paid_for_the_case_paper",
        "Are_you_existing_Myna_Beneficiary",
        "Chief_Complain_and_Case_History__",
        "Picosule__Picosule__Multivitamin_",
        "P___650__Parapic_650__Fepadol_650_",
        "Are_you_Myna_Mahila_Foundation_Staff_",
        "MV_Syrup__Zinprovit__Multivitamin_Syrup_",
        "Chief_Complain_and_Case_History__Cleaning",
        "Please_select_the_correct_option___Fever_",
        "Please_select_the_correct_option___Anemia_",
        "Please_select_the_correct_option___Vomiting_",
        "Please_select_the_correct_option___Weakness_",
        "Are_you_facing_these_issues___SRH___Mastitis_",
        "Are_you_facing_these_issues___Both___Mastitis_",
        "Are_you_facing_these_issues___SRH___Vaginitis_",
        "Are_you_facing_these_issues___Both___Vaginitis_",
        "Are_you_facing_these_issues___SRH___Cervicitis_",
        "Please_select_the_correct_option___SRH___Fever_",
        "Please_select_the_correct_option___Pelvic_pain_",
        "Are_you_facing_these_issues___Both___Cervicitis_",
        "Are_you_facing_these_issues___SRH___Breast_Pain_",
        "Please_select_the_correct_option___Both___Fever_",
        "Please_select_the_correct_option___SRH___Anemia_",
        "Are_you_facing_these_issues___Both___Breast_Pain_",
        "Are_you_facing_these_issues___SRH___Hysterectomy_",
        "Please_select_the_correct_option___Both___Anemia_",
        "Are_you_facing_these_issues___Both___Hysterectomy_",
        "Please_select_the_correct_option___SRH___Vomiting_",
        "Please_select_the_correct_option___SRH___Weakness_",
        "Please_select_the_correct_option___Heavy_bleeding_",
        "Are_you_facing_these_issues___SRH___Breast_Abscess_",
        "Please_select_the_correct_option___Both___Vomiting_",
        "Please_select_the_correct_option___Both___Weakness_",
        "Please_select_the_correct_option___Scanty_bleeding_",
        "Are_you_facing_these_issues___Both___Breast_Abscess_",
        "Are_you_facing_these_issues___SRH___Uterine_Fibroid_",
        "Are_you_facing_these_issues___Both___Uterine_Fibroid_",
        "Are_you_facing_these_issues___SRH___Fungal_infection_",
        "Please_select_the_correct_option___SRH___Pelvic_pain_",
        "Please_select_the_correct_option___Itching___Burning_",
        "Are_you_facing_these_issues___Both___Fungal_infection_",
        "Please_select_the_correct_option___Both___Pelvic_pain_",
        "Please_select_the_correct_option___SRH___Heavy_bleeding_",
        "Please_select_the_correct_option___Both___Heavy_bleeding_",
        "Please_select_the_correct_option___SRH___Scanty_bleeding_",
        "Please_select_the_correct_option___Both___Scanty_bleeding_",
        "Please_select_the_correct_option___SRH___Irregular_menses_",
        "Please_select_the_correct_option___Both___Irregular_menses_",
        "Please_select_the_correct_option___SRH___Itching___Burning_",
        "Please_select_the_correct_option___Both___Itching___Burning_",
        "Are_you_facing_these_issues___SRH___Breast_Structure__abnormali",
        "Are_you_facing_these_issues___Both___Breast_Structure__abnormal",
        "Treatment_status__if_the_patient_s_category_is_1st_or_more_foll"
    from source
)

select * from renamed